// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type WeatherForecast struct {
	// Time of the forecast in UTC/GMT
	Time string `json:"time"`
	// Temperature (2 m) in celsius
	Temperature float64 `json:"temperature"`
	// Precipitation (rain + showers + snow) in millimeter
	Precipitation float64 `json:"precipitation"`
	// Wind Speed (10 m) in Km/h
	WindSpeed float64 `json:"windSpeed"`
	// Wind Direction (10 m) in degrees
	WindDirection float64 `json:"windDirection"`
}

type WindFarm struct {
	// ID of the wind farm
	ID string `json:"id"`
	// Name of the wind farm
	Name string `json:"name"`
	// Latitude in degrees
	Latitude float64 `json:"latitude"`
	// Longitude in degrees
	Longitude float64 `json:"longitude"`
	// Provided forecasts from openmeteo for the weather
	WeatherForecasts []*WeatherForecast `json:"weatherForecasts"`
	// Is there precipitation at the wind farm today?
	HasPrecipitationToday bool `json:"hasPrecipitationToday"`
	// Elevation of the wind farm
	Elevation float64 `json:"elevation"`
}
